### ISSUE TITLE
Problems connecting the MPC9250 module with the library

### ISSUE THREAD

**Issue by brightproject** [bfrmd/EFIS-AHRS-AvionicsDuino#1]
Hello @bfrmd
I am studying your code, I planned to repeat on the microcontroller `stm32f401ccu6`, on which I create my aircraft instrument.
![photo1688111848](https://github.com/bfrmd/EFIS-AHRS-AvionicsDuino/assets/1788098/2383f104-bd90-4709-9bfa-99f1eee36df8)
But I [ran](https://github.com/bolderflight/invensense-imu/issues/120) into a problem in the operation of the `MPU9250` module and the [library](https://github.com/bolderflight/invensense-imu).
![Скриншот 10-07-2023 16 08 56](https://github.com/bfrmd/EFIS-AHRS-AvionicsDuino/assets/1788098/fed7edf1-2e31-4e1f-a44f-413afa944afe)
The same module works great with the [SparkFun](https://github.com/sparkfun/SparkFun_MPU-9250-DMP_Arduino_Library/tree/master/examples/MPU9250_DMP_Quaternion.ino) library.
![Скриншот 10-07-2023 15 48 13](https://github.com/bfrmd/EFIS-AHRS-AvionicsDuino/assets/1788098/adf72d2d-7dcd-42b7-9efe-3f783ee8374f)
So I don't understand what's wrong...
Perhaps you are planning to change the IMU module in your aircraft devices, from `MPU9250` to something new and produced?
Maybe sensor `GY-LSM6DS3`?
![6_osevoy-datchik-polozheniya-GY_LSM6DS3-_2v1_-akselerometr_-giroskop_](https://github.com/bolderflight/invensense-imu/assets/1788098/d7af3376-28c5-4f16-be1a-abdea70e4d7e)
Tell me, can't you calculate a `quaternion` without data from a magnetometer?
Therefore, do we need `accelerometer`, `gyroscope` and `magnetometer` sensors?

**Comment by bfrmd** [comment]
Hi Vladislav,
We do not use MPU9250. This InvenSensee 9DOF inertial unit is used in the examples provided with the UNav INS library, But it is obsolete and increasingly difficult to find. In addition, online sales sites are full of clones of dubious provenance that do not work. Therefore, we have adapted the software to use more modern and efficient STMicroelectronics sensors that are very easy to find on the market.
Have you read [this](https://avionicsduino.com/index.php/en/the-ahrs/)?
The uNav-INS library is extensively discussed [here](https://forum.pjrc.com/threads/48856-uNav-INS).

**Comment by brightproject** [comment]
> herefore, we have adapted the software to use more modern and efficient STMicroelectronics sensors that are very easy to find on the market.

This is great news!
I read the topic, but there are a lot of technical details, so understanding everything is a long time.
![AHRSV2-1024x589](https://github.com/bfrmd/EFIS-AHRS-AvionicsDuino/assets/1788098/ecea0e21-bba0-4f7e-8c67-6e68878bfa56)
I don't see a magnetometer in this photo, I only see an accelerometer + gyroscope board `LSM6DSOX`.
It turns out that you connected two boards to the `I2C` bus and use  in the [library](https://github.com/bolderflight/invensense-imu) code?
That's it, figured it out - you are using a ready-made IMU ADAFRUIT ADA-4517, this board contains an axel + gyroscope and a separate magnetometer chim.
And it's all on the bus, with two addresses.
```
//                SDA   --------------------->   SDA1 (pin 17)  résistance pull sur la carte Adafruit 
//                SCL   --------------------->   SCL1 (pin 16)  résistance pull sur la carte Adafruit
```
But even when two chips are on the same board and on the same `I2C` bus, you still work with them through two different libraries ... which is a little inconvenient.
But still better than using the outdated and `EOL` chip `mpu9250`.
```
Adafruit_LSM6DSOX lsm6ds;
Adafruit_LIS3MDL lis3mdl;
```
